### ISSUE TITLE
system.copySystemConfiguration is not supported with flakes

### ISSUE THREAD

**Issue by R0b0ty** [Misterio77/nix-starter-configs#40] opened 2023-07-30 21:20 UTC
First of all, **thank you** for sharing this with the community, especially a total _NixOS_ beginner like me.

I'm running nix (Nix) 2.13.3, _Stable_.  I believe I followed the instructions pertaining to the **Minimal** version, but obtained a **Failed assertions** error, as shown below.  You'll note that I modified the various, required files to include my personal info (as stated in the instructions).  I must have done something wrong, however.  Also note that I did **not** have _Home Manager_ enabled prior to following these instructions (don't know if that plays a role in the error).  **Can you please help?**

```shell
nix-config on  master [+] 
❯ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   flake.lock
	new file:   flake.nix
	new file:   home-manager/home.nix
	new file:   nixos/configuration.nix
	new file:   nixos/hardware-configuration.nix


nix-config on  master [+] 
❯ sudo nixos-rebuild switch --flake .#fastnix
warning: Git tree '/home/r0b0ty/Projects/nix-config' is dirty
building the system configuration...
warning: Git tree '/home/r0b0ty/Projects/nix-config' is dirty
error:
       Failed assertions:
       - system.copySystemConfiguration is not supported with flakes
(use '--show-trace' to show detailed location information)
```

**Comment by Misterio77** [comment] 2023-07-30 22:11
Hi! Thanks for your kind words, I'm glad that this project is useful to you :D

So, the problem is your config has a `system.copySystemConfiguration = true` somewhere. This option is not compatible with flakes, as it relies on NIXOS_PATH, which is impure. Just set it to false (the default) and it should work :)

If you have a specific use-case that requires this feature, let me know and I can perhaps point you to an equivalent that works with flakes.

Cheers

**Comment by R0b0ty** [comment] 2023-07-31 00:50
You were spot on, **thanks**!  I got a perfect rebuild after commenting that line out.

As I mentioned in the beginning, I didn't have _Home Manager_ installed and configured, so I had to go to the [Home Manager Manual](https://nix-community.github.io/home-manager/index.html#sec-install-standalone).  I figured that since your sample `flake.nix` file included a _homeConfigurations_ section, and a mention of it was in the instructions, that it was expected.  Maybe other noobs like me would benefit from mentioning the link above.  Apart from that, everything was just great.  Once again, thank you very much for sharing!

**Comment by Misterio77** [comment] 2023-09-16 21:31
Hey! Marking this as completed it's been addressed (a shell command is [provided on the readme](https://github.com/Misterio77/nix-starter-configs/blob/133826a072330e916691a1c236948cbdfec6250b/README.md?plain=1#L101) for getting `home-manager`). If anyone else faces this, do feel free to comment or reopen :)

**Closed by Misterio77** 2023-09-16 21:31 UTC
